<?xml version="1.0"?>
<robot 
  xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
  xmlns:plugin="http://playerstage.sourceforge.net/gazebo/xmlschema/#plugin"

	xmlns:xacro="http://ros.org/wiki/xacro" name="husky">
       
    <!-- Included URDF/XACRO Files -->

  <xacro:include filename="$(find husky_description)/urdf/base.urdf.xacro" />
  <xacro:include filename="$(find husky_description)/urdf/sensors/sick_laser.urdf.xacro" />
  <xacro:include filename="$(find husky_description)/urdf/sensors/gps.urdf.xacro" />
  <gazebo>
    <plugin name="imu_plugin" filename="libgazebo_ros_imu.so">
      <alwaysOn>true</alwaysOn>
      <bodyName>base_link</bodyName>
      <topicName>imu_data</topicName>
      <serviceName>imu_service</serviceName>
      <gaussianNoise>0.01</gaussianNoise>
    </plugin>
  </gazebo>


  <husky_part parent="base_footprint" name="user_plate" mesh="user_plate"
    colour="DarkGray"
    translateX="-0.35" translateY="-0.325" translateZ="${0.165 + wheel_x_size/2 - base_z_origin_to_wheel_origin}" 
    rotateX="1.5705" rotateY="0.0" rotateZ="1.5705"/>
  <gazebo reference="base_footprint_user_plate_part">
    <material>Gazebo/FlatBlack</material>
  </gazebo>

  <gazebo>
    <plugin name="gps_plugin" filename="libhusky_tudarmstadt_gps_plugin.so">
    <alwaysOn>true</alwaysOn>
        <updateRate>4.0</updateRate>
        <bodyName>base_link</bodyName>
        <topicName>navsat/fix</topicName>
        <velocityTopicName>navsat/fix_velocity</velocityTopicName>
        <drift>5.0 5.0 5.0</drift>
        <gaussianNoise>0.1 0.1 0.1</gaussianNoise>
        <velocityDrift>0 0 0</velocityDrift>
        <velocityGaussianNoise>0.1 0.1 0.1</velocityGaussianNoise>
        <referenceLatitude>43.409991</referenceLatitude>
        <referenceLongitude>-80.448362</referenceLongitude>
    </plugin> 
  </gazebo>


  <!--novatel_gps_sensor name="gps" gps_topic="gps" velocity_topic="gps_vel" lat="48" lon="-8.0" /-->

  <!-- This adds the laser macro, including the scan for gazebo and link name -->
  <sick_laser_v0 name="laser_scan" parent="base" ros_topic="scan"
    update_rate="20" min_angle="-1.57" max_angle="1.57" />
    
</robot>
